// SERIAL CODES
#define SERVICE_CHECK "SERVICE CHECK"
#define SEND_SUCCESSFULL "SEND_SUCCESSFULL"
#define SEND_ERROR "SEND_ERROR"
#define PARAMETER_ERROR "PARAMETER ERROR"
#define SENDING "SENDING... "
#define RESENDING "RESENDING..."

#define NETWORK_FAILURE "NETWORK_FAILURE"
#define GPRS_FAILURE "GPRS_FAILURE"
#define REMOTE_ERROR "REMOTE_ERROR"

#define GEN_ERROR "ERROR"

// MEMORY READ AND SEND
#define SLPIOT_MEM_LOG "MEM_LOG/SLPIOT/"
#define SLPIOT_DATA_LOG "DT_LOG/SLPIOT/"

#define ISTSOS_MEM_LOG "MEM_LOG/ISTSOS/"
#define ISTSOS_DATA_LOG "DT_LOG/ISTSOS/"
// SIM Code

#define SIM_800 "SIM 800"

